/*
GeoAPI

Testing TimezonesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package geoapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/geosearch-dev/geoapi-go"
)

func Test_geoapi_TimezonesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TimezonesAPIService GetTimezone", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tzId string

		resp, httpRes, err := apiClient.TimezonesAPI.GetTimezone(context.Background(), tzId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TimezonesAPIService ListTimezones", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TimezonesAPI.ListTimezones(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
