/*
GeoSearch

Testing BoundariesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package geosearch

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/geosearch-dev/geosearch-go"
)

func Test_geosearch_BoundariesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BoundariesAPIService GetBoundary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var geonameId int64

		resp, httpRes, err := apiClient.BoundariesAPI.GetBoundary(context.Background(), geonameId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
