/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the City type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &City{}

// City struct for City
type City struct {
	Id *int64 `json:"id,omitempty"`
	GeonameId *int64 `json:"geoname_id,omitempty"`
	Name *string `json:"name,omitempty"`
	AsciiName *string `json:"ascii_name,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	Admin1Code *string `json:"admin1_code,omitempty"`
	Admin2Code *string `json:"admin2_code,omitempty"`
	Population *int64 `json:"population,omitempty"`
	Elevation *int32 `json:"elevation,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
	Latitude *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
	Country *CountryRef `json:"country,omitempty"`
	Region *RegionRef `json:"region,omitempty"`
}

// NewCity instantiates a new City object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCity() *City {
	this := City{}
	return &this
}

// NewCityWithDefaults instantiates a new City object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCityWithDefaults() *City {
	this := City{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *City) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *City) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *City) SetId(v int64) {
	o.Id = &v
}

// GetGeonameId returns the GeonameId field value if set, zero value otherwise.
func (o *City) GetGeonameId() int64 {
	if o == nil || IsNil(o.GeonameId) {
		var ret int64
		return ret
	}
	return *o.GeonameId
}

// GetGeonameIdOk returns a tuple with the GeonameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetGeonameIdOk() (*int64, bool) {
	if o == nil || IsNil(o.GeonameId) {
		return nil, false
	}
	return o.GeonameId, true
}

// HasGeonameId returns a boolean if a field has been set.
func (o *City) HasGeonameId() bool {
	if o != nil && !IsNil(o.GeonameId) {
		return true
	}

	return false
}

// SetGeonameId gets a reference to the given int64 and assigns it to the GeonameId field.
func (o *City) SetGeonameId(v int64) {
	o.GeonameId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *City) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *City) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *City) SetName(v string) {
	o.Name = &v
}

// GetAsciiName returns the AsciiName field value if set, zero value otherwise.
func (o *City) GetAsciiName() string {
	if o == nil || IsNil(o.AsciiName) {
		var ret string
		return ret
	}
	return *o.AsciiName
}

// GetAsciiNameOk returns a tuple with the AsciiName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetAsciiNameOk() (*string, bool) {
	if o == nil || IsNil(o.AsciiName) {
		return nil, false
	}
	return o.AsciiName, true
}

// HasAsciiName returns a boolean if a field has been set.
func (o *City) HasAsciiName() bool {
	if o != nil && !IsNil(o.AsciiName) {
		return true
	}

	return false
}

// SetAsciiName gets a reference to the given string and assigns it to the AsciiName field.
func (o *City) SetAsciiName(v string) {
	o.AsciiName = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *City) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *City) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *City) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetAdmin1Code returns the Admin1Code field value if set, zero value otherwise.
func (o *City) GetAdmin1Code() string {
	if o == nil || IsNil(o.Admin1Code) {
		var ret string
		return ret
	}
	return *o.Admin1Code
}

// GetAdmin1CodeOk returns a tuple with the Admin1Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetAdmin1CodeOk() (*string, bool) {
	if o == nil || IsNil(o.Admin1Code) {
		return nil, false
	}
	return o.Admin1Code, true
}

// HasAdmin1Code returns a boolean if a field has been set.
func (o *City) HasAdmin1Code() bool {
	if o != nil && !IsNil(o.Admin1Code) {
		return true
	}

	return false
}

// SetAdmin1Code gets a reference to the given string and assigns it to the Admin1Code field.
func (o *City) SetAdmin1Code(v string) {
	o.Admin1Code = &v
}

// GetAdmin2Code returns the Admin2Code field value if set, zero value otherwise.
func (o *City) GetAdmin2Code() string {
	if o == nil || IsNil(o.Admin2Code) {
		var ret string
		return ret
	}
	return *o.Admin2Code
}

// GetAdmin2CodeOk returns a tuple with the Admin2Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetAdmin2CodeOk() (*string, bool) {
	if o == nil || IsNil(o.Admin2Code) {
		return nil, false
	}
	return o.Admin2Code, true
}

// HasAdmin2Code returns a boolean if a field has been set.
func (o *City) HasAdmin2Code() bool {
	if o != nil && !IsNil(o.Admin2Code) {
		return true
	}

	return false
}

// SetAdmin2Code gets a reference to the given string and assigns it to the Admin2Code field.
func (o *City) SetAdmin2Code(v string) {
	o.Admin2Code = &v
}

// GetPopulation returns the Population field value if set, zero value otherwise.
func (o *City) GetPopulation() int64 {
	if o == nil || IsNil(o.Population) {
		var ret int64
		return ret
	}
	return *o.Population
}

// GetPopulationOk returns a tuple with the Population field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetPopulationOk() (*int64, bool) {
	if o == nil || IsNil(o.Population) {
		return nil, false
	}
	return o.Population, true
}

// HasPopulation returns a boolean if a field has been set.
func (o *City) HasPopulation() bool {
	if o != nil && !IsNil(o.Population) {
		return true
	}

	return false
}

// SetPopulation gets a reference to the given int64 and assigns it to the Population field.
func (o *City) SetPopulation(v int64) {
	o.Population = &v
}

// GetElevation returns the Elevation field value if set, zero value otherwise.
func (o *City) GetElevation() int32 {
	if o == nil || IsNil(o.Elevation) {
		var ret int32
		return ret
	}
	return *o.Elevation
}

// GetElevationOk returns a tuple with the Elevation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetElevationOk() (*int32, bool) {
	if o == nil || IsNil(o.Elevation) {
		return nil, false
	}
	return o.Elevation, true
}

// HasElevation returns a boolean if a field has been set.
func (o *City) HasElevation() bool {
	if o != nil && !IsNil(o.Elevation) {
		return true
	}

	return false
}

// SetElevation gets a reference to the given int32 and assigns it to the Elevation field.
func (o *City) SetElevation(v int32) {
	o.Elevation = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *City) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *City) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *City) SetTimezone(v string) {
	o.Timezone = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *City) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *City) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *City) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *City) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *City) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *City) SetLongitude(v float64) {
	o.Longitude = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *City) GetCountry() CountryRef {
	if o == nil || IsNil(o.Country) {
		var ret CountryRef
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetCountryOk() (*CountryRef, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *City) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given CountryRef and assigns it to the Country field.
func (o *City) SetCountry(v CountryRef) {
	o.Country = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *City) GetRegion() RegionRef {
	if o == nil || IsNil(o.Region) {
		var ret RegionRef
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *City) GetRegionOk() (*RegionRef, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *City) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given RegionRef and assigns it to the Region field.
func (o *City) SetRegion(v RegionRef) {
	o.Region = &v
}

func (o City) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o City) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.GeonameId) {
		toSerialize["geoname_id"] = o.GeonameId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AsciiName) {
		toSerialize["ascii_name"] = o.AsciiName
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.Admin1Code) {
		toSerialize["admin1_code"] = o.Admin1Code
	}
	if !IsNil(o.Admin2Code) {
		toSerialize["admin2_code"] = o.Admin2Code
	}
	if !IsNil(o.Population) {
		toSerialize["population"] = o.Population
	}
	if !IsNil(o.Elevation) {
		toSerialize["elevation"] = o.Elevation
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

type NullableCity struct {
	value *City
	isSet bool
}

func (v NullableCity) Get() *City {
	return v.value
}

func (v *NullableCity) Set(val *City) {
	v.value = val
	v.isSet = true
}

func (v NullableCity) IsSet() bool {
	return v.isSet
}

func (v *NullableCity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCity(val *City) *NullableCity {
	return &NullableCity{value: val, isSet: true}
}

func (v NullableCity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


