/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the GetStatus200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStatus200ResponseData{}

// GetStatus200ResponseData struct for GetStatus200ResponseData
type GetStatus200ResponseData struct {
	Status *string `json:"status,omitempty"`
	Database *string `json:"database,omitempty"`
}

// NewGetStatus200ResponseData instantiates a new GetStatus200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStatus200ResponseData() *GetStatus200ResponseData {
	this := GetStatus200ResponseData{}
	return &this
}

// NewGetStatus200ResponseDataWithDefaults instantiates a new GetStatus200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStatus200ResponseDataWithDefaults() *GetStatus200ResponseData {
	this := GetStatus200ResponseData{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetStatus200ResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatus200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetStatus200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetStatus200ResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetDatabase returns the Database field value if set, zero value otherwise.
func (o *GetStatus200ResponseData) GetDatabase() string {
	if o == nil || IsNil(o.Database) {
		var ret string
		return ret
	}
	return *o.Database
}

// GetDatabaseOk returns a tuple with the Database field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatus200ResponseData) GetDatabaseOk() (*string, bool) {
	if o == nil || IsNil(o.Database) {
		return nil, false
	}
	return o.Database, true
}

// HasDatabase returns a boolean if a field has been set.
func (o *GetStatus200ResponseData) HasDatabase() bool {
	if o != nil && !IsNil(o.Database) {
		return true
	}

	return false
}

// SetDatabase gets a reference to the given string and assigns it to the Database field.
func (o *GetStatus200ResponseData) SetDatabase(v string) {
	o.Database = &v
}

func (o GetStatus200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStatus200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Database) {
		toSerialize["database"] = o.Database
	}
	return toSerialize, nil
}

type NullableGetStatus200ResponseData struct {
	value *GetStatus200ResponseData
	isSet bool
}

func (v NullableGetStatus200ResponseData) Get() *GetStatus200ResponseData {
	return v.value
}

func (v *NullableGetStatus200ResponseData) Set(val *GetStatus200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatus200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatus200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatus200ResponseData(val *GetStatus200ResponseData) *NullableGetStatus200ResponseData {
	return &NullableGetStatus200ResponseData{value: val, isSet: true}
}

func (v NullableGetStatus200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatus200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


