/*
GeoAPI

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geoapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchRequest{}

// BatchRequest struct for BatchRequest
type BatchRequest struct {
	// Array of entity IDs to look up (max 50)
	Ids []int64 `json:"ids"`
}

type _BatchRequest BatchRequest

// NewBatchRequest instantiates a new BatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchRequest(ids []int64) *BatchRequest {
	this := BatchRequest{}
	this.Ids = ids
	return &this
}

// NewBatchRequestWithDefaults instantiates a new BatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchRequestWithDefaults() *BatchRequest {
	this := BatchRequest{}
	return &this
}

// GetIds returns the Ids field value
func (o *BatchRequest) GetIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *BatchRequest) GetIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *BatchRequest) SetIds(v []int64) {
	o.Ids = v
}

func (o BatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	return toSerialize, nil
}

func (o *BatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchRequest := _BatchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchRequest)

	if err != nil {
		return err
	}

	*o = BatchRequest(varBatchRequest)

	return err
}

type NullableBatchRequest struct {
	value *BatchRequest
	isSet bool
}

func (v NullableBatchRequest) Get() *BatchRequest {
	return v.value
}

func (v *NullableBatchRequest) Set(val *BatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchRequest(val *BatchRequest) *NullableBatchRequest {
	return &NullableBatchRequest{value: val, isSet: true}
}

func (v NullableBatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


