/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.2
Contact: info@geosearch.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the PostalCodeListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostalCodeListResponse{}

// PostalCodeListResponse struct for PostalCodeListResponse
type PostalCodeListResponse struct {
	Data []PostalCode `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// NewPostalCodeListResponse instantiates a new PostalCodeListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostalCodeListResponse() *PostalCodeListResponse {
	this := PostalCodeListResponse{}
	return &this
}

// NewPostalCodeListResponseWithDefaults instantiates a new PostalCodeListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostalCodeListResponseWithDefaults() *PostalCodeListResponse {
	this := PostalCodeListResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PostalCodeListResponse) GetData() []PostalCode {
	if o == nil || IsNil(o.Data) {
		var ret []PostalCode
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCodeListResponse) GetDataOk() ([]PostalCode, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PostalCodeListResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []PostalCode and assigns it to the Data field.
func (o *PostalCodeListResponse) SetData(v []PostalCode) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *PostalCodeListResponse) GetMeta() PaginationMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PaginationMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCodeListResponse) GetMetaOk() (*PaginationMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *PostalCodeListResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginationMeta and assigns it to the Meta field.
func (o *PostalCodeListResponse) SetMeta(v PaginationMeta) {
	o.Meta = &v
}

func (o PostalCodeListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostalCodeListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullablePostalCodeListResponse struct {
	value *PostalCodeListResponse
	isSet bool
}

func (v NullablePostalCodeListResponse) Get() *PostalCodeListResponse {
	return v.value
}

func (v *NullablePostalCodeListResponse) Set(val *PostalCodeListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostalCodeListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostalCodeListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostalCodeListResponse(val *PostalCodeListResponse) *NullablePostalCodeListResponse {
	return &NullablePostalCodeListResponse{value: val, isSet: true}
}

func (v NullablePostalCodeListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostalCodeListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


