/*
GeoAPI

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geoapi

import (
	"encoding/json"
)

// checks if the NearbyCity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NearbyCity{}

// NearbyCity struct for NearbyCity
type NearbyCity struct {
	Id *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	Population *int64 `json:"population,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
	Latitude *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
	DistanceKm *float64 `json:"distance_km,omitempty"`
	Country *CountryRef `json:"country,omitempty"`
	Region *RegionRef `json:"region,omitempty"`
}

// NewNearbyCity instantiates a new NearbyCity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNearbyCity() *NearbyCity {
	this := NearbyCity{}
	return &this
}

// NewNearbyCityWithDefaults instantiates a new NearbyCity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNearbyCityWithDefaults() *NearbyCity {
	this := NearbyCity{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NearbyCity) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NearbyCity) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *NearbyCity) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NearbyCity) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NearbyCity) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NearbyCity) SetName(v string) {
	o.Name = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *NearbyCity) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *NearbyCity) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *NearbyCity) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetPopulation returns the Population field value if set, zero value otherwise.
func (o *NearbyCity) GetPopulation() int64 {
	if o == nil || IsNil(o.Population) {
		var ret int64
		return ret
	}
	return *o.Population
}

// GetPopulationOk returns a tuple with the Population field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetPopulationOk() (*int64, bool) {
	if o == nil || IsNil(o.Population) {
		return nil, false
	}
	return o.Population, true
}

// HasPopulation returns a boolean if a field has been set.
func (o *NearbyCity) HasPopulation() bool {
	if o != nil && !IsNil(o.Population) {
		return true
	}

	return false
}

// SetPopulation gets a reference to the given int64 and assigns it to the Population field.
func (o *NearbyCity) SetPopulation(v int64) {
	o.Population = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *NearbyCity) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *NearbyCity) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *NearbyCity) SetTimezone(v string) {
	o.Timezone = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *NearbyCity) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *NearbyCity) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *NearbyCity) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *NearbyCity) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *NearbyCity) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *NearbyCity) SetLongitude(v float64) {
	o.Longitude = &v
}

// GetDistanceKm returns the DistanceKm field value if set, zero value otherwise.
func (o *NearbyCity) GetDistanceKm() float64 {
	if o == nil || IsNil(o.DistanceKm) {
		var ret float64
		return ret
	}
	return *o.DistanceKm
}

// GetDistanceKmOk returns a tuple with the DistanceKm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetDistanceKmOk() (*float64, bool) {
	if o == nil || IsNil(o.DistanceKm) {
		return nil, false
	}
	return o.DistanceKm, true
}

// HasDistanceKm returns a boolean if a field has been set.
func (o *NearbyCity) HasDistanceKm() bool {
	if o != nil && !IsNil(o.DistanceKm) {
		return true
	}

	return false
}

// SetDistanceKm gets a reference to the given float64 and assigns it to the DistanceKm field.
func (o *NearbyCity) SetDistanceKm(v float64) {
	o.DistanceKm = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *NearbyCity) GetCountry() CountryRef {
	if o == nil || IsNil(o.Country) {
		var ret CountryRef
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetCountryOk() (*CountryRef, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *NearbyCity) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given CountryRef and assigns it to the Country field.
func (o *NearbyCity) SetCountry(v CountryRef) {
	o.Country = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *NearbyCity) GetRegion() RegionRef {
	if o == nil || IsNil(o.Region) {
		var ret RegionRef
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NearbyCity) GetRegionOk() (*RegionRef, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *NearbyCity) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given RegionRef and assigns it to the Region field.
func (o *NearbyCity) SetRegion(v RegionRef) {
	o.Region = &v
}

func (o NearbyCity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NearbyCity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.Population) {
		toSerialize["population"] = o.Population
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.DistanceKm) {
		toSerialize["distance_km"] = o.DistanceKm
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

type NullableNearbyCity struct {
	value *NearbyCity
	isSet bool
}

func (v NullableNearbyCity) Get() *NearbyCity {
	return v.value
}

func (v *NullableNearbyCity) Set(val *NearbyCity) {
	v.value = val
	v.isSet = true
}

func (v NullableNearbyCity) IsSet() bool {
	return v.isSet
}

func (v *NullableNearbyCity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNearbyCity(val *NearbyCity) *NullableNearbyCity {
	return &NullableNearbyCity{value: val, isSet: true}
}

func (v NullableNearbyCity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNearbyCity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


