/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.2
Contact: info@geosearch.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the GeoJSONMultiPolygon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoJSONMultiPolygon{}

// GeoJSONMultiPolygon GeoJSON MultiPolygon geometry.  WHEN IT IS RETURNED DEPENDS ON THE ENDPOINT AND ON THE PLAN, and there is no single rule. The previous wording here — \"only returned when explicitly requested via `?fields=geometry`\" — was false in both directions and is corrected below.  `GET /v1/countries/{code}` and `GET /v1/regions/{id}`: returned by default. These are detail endpoints and they have always served geometry without `?fields=geometry` being present.  `GET /v1/countries`, `GET /v1/regions` and `GET /v1/countries/{code}/regions`: returned only when `?fields=geometry` is requested. Omitting it from a list response is a payload decision — a 100-row page of region polygons is several megabytes.  REGION GEOMETRY ADDITIONALLY REQUIRES A PAID PLAN. On `GET /v1/regions/{id}`, `GET /v1/regions?fields=geometry` and `GET /v1/countries/{code}/regions?fields=geometry`, the `geometry` key is OMITTED ENTIRELY for Free-tier keys — absent, not null. Country geometry is not gated: `GET /v1/countries/{code}` and `GET /v1/countries?fields=geometry` serve it on every plan, including Free.  The omission is silent by design: it is not an error, and these endpoints still return 200. A client that reads `data.geometry.type` without checking for the key will fail on a null dereference rather than receive a typed zero. To fetch a boundary polygon explicitly — and to receive a 403 with an upgrade link rather than a silent omission when the plan does not include it — use `GET /v1/boundaries/{geoname_id}`.
type GeoJSONMultiPolygon struct {
	Type *string `json:"type,omitempty"`
	Coordinates [][][][]float64 `json:"coordinates,omitempty"`
}

// NewGeoJSONMultiPolygon instantiates a new GeoJSONMultiPolygon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoJSONMultiPolygon() *GeoJSONMultiPolygon {
	this := GeoJSONMultiPolygon{}
	return &this
}

// NewGeoJSONMultiPolygonWithDefaults instantiates a new GeoJSONMultiPolygon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoJSONMultiPolygonWithDefaults() *GeoJSONMultiPolygon {
	this := GeoJSONMultiPolygon{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GeoJSONMultiPolygon) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONMultiPolygon) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GeoJSONMultiPolygon) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GeoJSONMultiPolygon) SetType(v string) {
	o.Type = &v
}

// GetCoordinates returns the Coordinates field value if set, zero value otherwise.
func (o *GeoJSONMultiPolygon) GetCoordinates() [][][][]float64 {
	if o == nil || IsNil(o.Coordinates) {
		var ret [][][][]float64
		return ret
	}
	return o.Coordinates
}

// GetCoordinatesOk returns a tuple with the Coordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONMultiPolygon) GetCoordinatesOk() ([][][][]float64, bool) {
	if o == nil || IsNil(o.Coordinates) {
		return nil, false
	}
	return o.Coordinates, true
}

// HasCoordinates returns a boolean if a field has been set.
func (o *GeoJSONMultiPolygon) HasCoordinates() bool {
	if o != nil && !IsNil(o.Coordinates) {
		return true
	}

	return false
}

// SetCoordinates gets a reference to the given [][][][]float64 and assigns it to the Coordinates field.
func (o *GeoJSONMultiPolygon) SetCoordinates(v [][][][]float64) {
	o.Coordinates = v
}

func (o GeoJSONMultiPolygon) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoJSONMultiPolygon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Coordinates) {
		toSerialize["coordinates"] = o.Coordinates
	}
	return toSerialize, nil
}

type NullableGeoJSONMultiPolygon struct {
	value *GeoJSONMultiPolygon
	isSet bool
}

func (v NullableGeoJSONMultiPolygon) Get() *GeoJSONMultiPolygon {
	return v.value
}

func (v *NullableGeoJSONMultiPolygon) Set(val *GeoJSONMultiPolygon) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoJSONMultiPolygon) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoJSONMultiPolygon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoJSONMultiPolygon(val *GeoJSONMultiPolygon) *NullableGeoJSONMultiPolygon {
	return &NullableGeoJSONMultiPolygon{value: val, isSet: true}
}

func (v NullableGeoJSONMultiPolygon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoJSONMultiPolygon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


