/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.2
Contact: info@geosearch.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the ErrorResponseErrorDetailsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorResponseErrorDetailsInner{}

// ErrorResponseErrorDetailsInner struct for ErrorResponseErrorDetailsInner
type ErrorResponseErrorDetailsInner struct {
	Field *string `json:"field,omitempty"`
	Issue *string `json:"issue,omitempty"`
}

// NewErrorResponseErrorDetailsInner instantiates a new ErrorResponseErrorDetailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorResponseErrorDetailsInner() *ErrorResponseErrorDetailsInner {
	this := ErrorResponseErrorDetailsInner{}
	return &this
}

// NewErrorResponseErrorDetailsInnerWithDefaults instantiates a new ErrorResponseErrorDetailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorResponseErrorDetailsInnerWithDefaults() *ErrorResponseErrorDetailsInner {
	this := ErrorResponseErrorDetailsInner{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *ErrorResponseErrorDetailsInner) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorResponseErrorDetailsInner) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *ErrorResponseErrorDetailsInner) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *ErrorResponseErrorDetailsInner) SetField(v string) {
	o.Field = &v
}

// GetIssue returns the Issue field value if set, zero value otherwise.
func (o *ErrorResponseErrorDetailsInner) GetIssue() string {
	if o == nil || IsNil(o.Issue) {
		var ret string
		return ret
	}
	return *o.Issue
}

// GetIssueOk returns a tuple with the Issue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorResponseErrorDetailsInner) GetIssueOk() (*string, bool) {
	if o == nil || IsNil(o.Issue) {
		return nil, false
	}
	return o.Issue, true
}

// HasIssue returns a boolean if a field has been set.
func (o *ErrorResponseErrorDetailsInner) HasIssue() bool {
	if o != nil && !IsNil(o.Issue) {
		return true
	}

	return false
}

// SetIssue gets a reference to the given string and assigns it to the Issue field.
func (o *ErrorResponseErrorDetailsInner) SetIssue(v string) {
	o.Issue = &v
}

func (o ErrorResponseErrorDetailsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorResponseErrorDetailsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Issue) {
		toSerialize["issue"] = o.Issue
	}
	return toSerialize, nil
}

type NullableErrorResponseErrorDetailsInner struct {
	value *ErrorResponseErrorDetailsInner
	isSet bool
}

func (v NullableErrorResponseErrorDetailsInner) Get() *ErrorResponseErrorDetailsInner {
	return v.value
}

func (v *NullableErrorResponseErrorDetailsInner) Set(val *ErrorResponseErrorDetailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorResponseErrorDetailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorResponseErrorDetailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorResponseErrorDetailsInner(val *ErrorResponseErrorDetailsInner) *NullableErrorResponseErrorDetailsInner {
	return &NullableErrorResponseErrorDetailsInner{value: val, isSet: true}
}

func (v NullableErrorResponseErrorDetailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorResponseErrorDetailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


