/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.2
Contact: info@geosearch.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the PostalCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostalCode{}

// PostalCode struct for PostalCode
type PostalCode struct {
	Id *int64 `json:"id,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	PostalCode *string `json:"postal_code,omitempty"`
	PlaceName *string `json:"place_name,omitempty"`
	AdminName1 *string `json:"admin_name1,omitempty"`
	AdminCode1 *string `json:"admin_code1,omitempty"`
	AdminName2 *string `json:"admin_name2,omitempty"`
	AdminCode2 *string `json:"admin_code2,omitempty"`
	// Third-level administrative area. Empty where the source data defines none — most US rows, including this example.
	AdminName3 *string `json:"admin_name3,omitempty"`
	// Third-level administrative code. Empty where the source data defines none — most US rows, including this example.
	AdminCode3 *string `json:"admin_code3,omitempty"`
	Latitude *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
	Accuracy *int32 `json:"accuracy,omitempty"`
	Country *CountryRef `json:"country,omitempty"`
}

// NewPostalCode instantiates a new PostalCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostalCode() *PostalCode {
	this := PostalCode{}
	return &this
}

// NewPostalCodeWithDefaults instantiates a new PostalCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostalCodeWithDefaults() *PostalCode {
	this := PostalCode{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PostalCode) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PostalCode) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *PostalCode) SetId(v int64) {
	o.Id = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *PostalCode) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *PostalCode) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *PostalCode) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *PostalCode) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *PostalCode) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *PostalCode) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetPlaceName returns the PlaceName field value if set, zero value otherwise.
func (o *PostalCode) GetPlaceName() string {
	if o == nil || IsNil(o.PlaceName) {
		var ret string
		return ret
	}
	return *o.PlaceName
}

// GetPlaceNameOk returns a tuple with the PlaceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetPlaceNameOk() (*string, bool) {
	if o == nil || IsNil(o.PlaceName) {
		return nil, false
	}
	return o.PlaceName, true
}

// HasPlaceName returns a boolean if a field has been set.
func (o *PostalCode) HasPlaceName() bool {
	if o != nil && !IsNil(o.PlaceName) {
		return true
	}

	return false
}

// SetPlaceName gets a reference to the given string and assigns it to the PlaceName field.
func (o *PostalCode) SetPlaceName(v string) {
	o.PlaceName = &v
}

// GetAdminName1 returns the AdminName1 field value if set, zero value otherwise.
func (o *PostalCode) GetAdminName1() string {
	if o == nil || IsNil(o.AdminName1) {
		var ret string
		return ret
	}
	return *o.AdminName1
}

// GetAdminName1Ok returns a tuple with the AdminName1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetAdminName1Ok() (*string, bool) {
	if o == nil || IsNil(o.AdminName1) {
		return nil, false
	}
	return o.AdminName1, true
}

// HasAdminName1 returns a boolean if a field has been set.
func (o *PostalCode) HasAdminName1() bool {
	if o != nil && !IsNil(o.AdminName1) {
		return true
	}

	return false
}

// SetAdminName1 gets a reference to the given string and assigns it to the AdminName1 field.
func (o *PostalCode) SetAdminName1(v string) {
	o.AdminName1 = &v
}

// GetAdminCode1 returns the AdminCode1 field value if set, zero value otherwise.
func (o *PostalCode) GetAdminCode1() string {
	if o == nil || IsNil(o.AdminCode1) {
		var ret string
		return ret
	}
	return *o.AdminCode1
}

// GetAdminCode1Ok returns a tuple with the AdminCode1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetAdminCode1Ok() (*string, bool) {
	if o == nil || IsNil(o.AdminCode1) {
		return nil, false
	}
	return o.AdminCode1, true
}

// HasAdminCode1 returns a boolean if a field has been set.
func (o *PostalCode) HasAdminCode1() bool {
	if o != nil && !IsNil(o.AdminCode1) {
		return true
	}

	return false
}

// SetAdminCode1 gets a reference to the given string and assigns it to the AdminCode1 field.
func (o *PostalCode) SetAdminCode1(v string) {
	o.AdminCode1 = &v
}

// GetAdminName2 returns the AdminName2 field value if set, zero value otherwise.
func (o *PostalCode) GetAdminName2() string {
	if o == nil || IsNil(o.AdminName2) {
		var ret string
		return ret
	}
	return *o.AdminName2
}

// GetAdminName2Ok returns a tuple with the AdminName2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetAdminName2Ok() (*string, bool) {
	if o == nil || IsNil(o.AdminName2) {
		return nil, false
	}
	return o.AdminName2, true
}

// HasAdminName2 returns a boolean if a field has been set.
func (o *PostalCode) HasAdminName2() bool {
	if o != nil && !IsNil(o.AdminName2) {
		return true
	}

	return false
}

// SetAdminName2 gets a reference to the given string and assigns it to the AdminName2 field.
func (o *PostalCode) SetAdminName2(v string) {
	o.AdminName2 = &v
}

// GetAdminCode2 returns the AdminCode2 field value if set, zero value otherwise.
func (o *PostalCode) GetAdminCode2() string {
	if o == nil || IsNil(o.AdminCode2) {
		var ret string
		return ret
	}
	return *o.AdminCode2
}

// GetAdminCode2Ok returns a tuple with the AdminCode2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetAdminCode2Ok() (*string, bool) {
	if o == nil || IsNil(o.AdminCode2) {
		return nil, false
	}
	return o.AdminCode2, true
}

// HasAdminCode2 returns a boolean if a field has been set.
func (o *PostalCode) HasAdminCode2() bool {
	if o != nil && !IsNil(o.AdminCode2) {
		return true
	}

	return false
}

// SetAdminCode2 gets a reference to the given string and assigns it to the AdminCode2 field.
func (o *PostalCode) SetAdminCode2(v string) {
	o.AdminCode2 = &v
}

// GetAdminName3 returns the AdminName3 field value if set, zero value otherwise.
func (o *PostalCode) GetAdminName3() string {
	if o == nil || IsNil(o.AdminName3) {
		var ret string
		return ret
	}
	return *o.AdminName3
}

// GetAdminName3Ok returns a tuple with the AdminName3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetAdminName3Ok() (*string, bool) {
	if o == nil || IsNil(o.AdminName3) {
		return nil, false
	}
	return o.AdminName3, true
}

// HasAdminName3 returns a boolean if a field has been set.
func (o *PostalCode) HasAdminName3() bool {
	if o != nil && !IsNil(o.AdminName3) {
		return true
	}

	return false
}

// SetAdminName3 gets a reference to the given string and assigns it to the AdminName3 field.
func (o *PostalCode) SetAdminName3(v string) {
	o.AdminName3 = &v
}

// GetAdminCode3 returns the AdminCode3 field value if set, zero value otherwise.
func (o *PostalCode) GetAdminCode3() string {
	if o == nil || IsNil(o.AdminCode3) {
		var ret string
		return ret
	}
	return *o.AdminCode3
}

// GetAdminCode3Ok returns a tuple with the AdminCode3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetAdminCode3Ok() (*string, bool) {
	if o == nil || IsNil(o.AdminCode3) {
		return nil, false
	}
	return o.AdminCode3, true
}

// HasAdminCode3 returns a boolean if a field has been set.
func (o *PostalCode) HasAdminCode3() bool {
	if o != nil && !IsNil(o.AdminCode3) {
		return true
	}

	return false
}

// SetAdminCode3 gets a reference to the given string and assigns it to the AdminCode3 field.
func (o *PostalCode) SetAdminCode3(v string) {
	o.AdminCode3 = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *PostalCode) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *PostalCode) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *PostalCode) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *PostalCode) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *PostalCode) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *PostalCode) SetLongitude(v float64) {
	o.Longitude = &v
}

// GetAccuracy returns the Accuracy field value if set, zero value otherwise.
func (o *PostalCode) GetAccuracy() int32 {
	if o == nil || IsNil(o.Accuracy) {
		var ret int32
		return ret
	}
	return *o.Accuracy
}

// GetAccuracyOk returns a tuple with the Accuracy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetAccuracyOk() (*int32, bool) {
	if o == nil || IsNil(o.Accuracy) {
		return nil, false
	}
	return o.Accuracy, true
}

// HasAccuracy returns a boolean if a field has been set.
func (o *PostalCode) HasAccuracy() bool {
	if o != nil && !IsNil(o.Accuracy) {
		return true
	}

	return false
}

// SetAccuracy gets a reference to the given int32 and assigns it to the Accuracy field.
func (o *PostalCode) SetAccuracy(v int32) {
	o.Accuracy = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *PostalCode) GetCountry() CountryRef {
	if o == nil || IsNil(o.Country) {
		var ret CountryRef
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostalCode) GetCountryOk() (*CountryRef, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *PostalCode) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given CountryRef and assigns it to the Country field.
func (o *PostalCode) SetCountry(v CountryRef) {
	o.Country = &v
}

func (o PostalCode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostalCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postal_code"] = o.PostalCode
	}
	if !IsNil(o.PlaceName) {
		toSerialize["place_name"] = o.PlaceName
	}
	if !IsNil(o.AdminName1) {
		toSerialize["admin_name1"] = o.AdminName1
	}
	if !IsNil(o.AdminCode1) {
		toSerialize["admin_code1"] = o.AdminCode1
	}
	if !IsNil(o.AdminName2) {
		toSerialize["admin_name2"] = o.AdminName2
	}
	if !IsNil(o.AdminCode2) {
		toSerialize["admin_code2"] = o.AdminCode2
	}
	if !IsNil(o.AdminName3) {
		toSerialize["admin_name3"] = o.AdminName3
	}
	if !IsNil(o.AdminCode3) {
		toSerialize["admin_code3"] = o.AdminCode3
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.Accuracy) {
		toSerialize["accuracy"] = o.Accuracy
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	return toSerialize, nil
}

type NullablePostalCode struct {
	value *PostalCode
	isSet bool
}

func (v NullablePostalCode) Get() *PostalCode {
	return v.value
}

func (v *NullablePostalCode) Set(val *PostalCode) {
	v.value = val
	v.isSet = true
}

func (v NullablePostalCode) IsSet() bool {
	return v.isSet
}

func (v *NullablePostalCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostalCode(val *PostalCode) *NullablePostalCode {
	return &NullablePostalCode{value: val, isSet: true}
}

func (v NullablePostalCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostalCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


