/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, and timezones through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.3
Contact: info@geosearch.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the Region type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Region{}

// Region struct for Region
type Region struct {
	Id *int64 `json:"id,omitempty"`
	GeonameId *int64 `json:"geoname_id,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	AdminCode *string `json:"admin_code,omitempty"`
	Name *string `json:"name,omitempty"`
	AsciiName *string `json:"ascii_name,omitempty"`
	Level *int32 `json:"level,omitempty"`
	ParentGeonameId *int64 `json:"parent_geoname_id,omitempty"`
	Population *int64 `json:"population,omitempty"`
	Latitude *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
	Country *CountryRef `json:"country,omitempty"`
	// Region boundary. Returned by default on `GET /v1/regions/{id}`, and on request via `?fields=geometry` on `GET /v1/regions` and `GET /v1/countries/{code}/regions`.  REQUIRES A PAID PLAN. On all three of those routes this key is OMITTED ENTIRELY for a Free-tier key — absent, not null, with a 200 status and no error. A client reading `data.geometry.type` unconditionally will fail on a null dereference.  To be told explicitly rather than silently, request the polygon from `GET /v1/boundaries/{geoname_id}`, which answers a Free key with a 403 and an upgrade link.
	Geometry *GeoJSONMultiPolygon `json:"geometry,omitempty"`
}

// NewRegion instantiates a new Region object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegion() *Region {
	this := Region{}
	return &this
}

// NewRegionWithDefaults instantiates a new Region object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionWithDefaults() *Region {
	this := Region{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Region) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Region) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Region) SetId(v int64) {
	o.Id = &v
}

// GetGeonameId returns the GeonameId field value if set, zero value otherwise.
func (o *Region) GetGeonameId() int64 {
	if o == nil || IsNil(o.GeonameId) {
		var ret int64
		return ret
	}
	return *o.GeonameId
}

// GetGeonameIdOk returns a tuple with the GeonameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetGeonameIdOk() (*int64, bool) {
	if o == nil || IsNil(o.GeonameId) {
		return nil, false
	}
	return o.GeonameId, true
}

// HasGeonameId returns a boolean if a field has been set.
func (o *Region) HasGeonameId() bool {
	if o != nil && !IsNil(o.GeonameId) {
		return true
	}

	return false
}

// SetGeonameId gets a reference to the given int64 and assigns it to the GeonameId field.
func (o *Region) SetGeonameId(v int64) {
	o.GeonameId = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *Region) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *Region) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *Region) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetAdminCode returns the AdminCode field value if set, zero value otherwise.
func (o *Region) GetAdminCode() string {
	if o == nil || IsNil(o.AdminCode) {
		var ret string
		return ret
	}
	return *o.AdminCode
}

// GetAdminCodeOk returns a tuple with the AdminCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetAdminCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AdminCode) {
		return nil, false
	}
	return o.AdminCode, true
}

// HasAdminCode returns a boolean if a field has been set.
func (o *Region) HasAdminCode() bool {
	if o != nil && !IsNil(o.AdminCode) {
		return true
	}

	return false
}

// SetAdminCode gets a reference to the given string and assigns it to the AdminCode field.
func (o *Region) SetAdminCode(v string) {
	o.AdminCode = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Region) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Region) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Region) SetName(v string) {
	o.Name = &v
}

// GetAsciiName returns the AsciiName field value if set, zero value otherwise.
func (o *Region) GetAsciiName() string {
	if o == nil || IsNil(o.AsciiName) {
		var ret string
		return ret
	}
	return *o.AsciiName
}

// GetAsciiNameOk returns a tuple with the AsciiName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetAsciiNameOk() (*string, bool) {
	if o == nil || IsNil(o.AsciiName) {
		return nil, false
	}
	return o.AsciiName, true
}

// HasAsciiName returns a boolean if a field has been set.
func (o *Region) HasAsciiName() bool {
	if o != nil && !IsNil(o.AsciiName) {
		return true
	}

	return false
}

// SetAsciiName gets a reference to the given string and assigns it to the AsciiName field.
func (o *Region) SetAsciiName(v string) {
	o.AsciiName = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *Region) GetLevel() int32 {
	if o == nil || IsNil(o.Level) {
		var ret int32
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *Region) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int32 and assigns it to the Level field.
func (o *Region) SetLevel(v int32) {
	o.Level = &v
}

// GetParentGeonameId returns the ParentGeonameId field value if set, zero value otherwise.
func (o *Region) GetParentGeonameId() int64 {
	if o == nil || IsNil(o.ParentGeonameId) {
		var ret int64
		return ret
	}
	return *o.ParentGeonameId
}

// GetParentGeonameIdOk returns a tuple with the ParentGeonameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetParentGeonameIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ParentGeonameId) {
		return nil, false
	}
	return o.ParentGeonameId, true
}

// HasParentGeonameId returns a boolean if a field has been set.
func (o *Region) HasParentGeonameId() bool {
	if o != nil && !IsNil(o.ParentGeonameId) {
		return true
	}

	return false
}

// SetParentGeonameId gets a reference to the given int64 and assigns it to the ParentGeonameId field.
func (o *Region) SetParentGeonameId(v int64) {
	o.ParentGeonameId = &v
}

// GetPopulation returns the Population field value if set, zero value otherwise.
func (o *Region) GetPopulation() int64 {
	if o == nil || IsNil(o.Population) {
		var ret int64
		return ret
	}
	return *o.Population
}

// GetPopulationOk returns a tuple with the Population field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetPopulationOk() (*int64, bool) {
	if o == nil || IsNil(o.Population) {
		return nil, false
	}
	return o.Population, true
}

// HasPopulation returns a boolean if a field has been set.
func (o *Region) HasPopulation() bool {
	if o != nil && !IsNil(o.Population) {
		return true
	}

	return false
}

// SetPopulation gets a reference to the given int64 and assigns it to the Population field.
func (o *Region) SetPopulation(v int64) {
	o.Population = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *Region) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *Region) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *Region) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *Region) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *Region) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *Region) SetLongitude(v float64) {
	o.Longitude = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *Region) GetCountry() CountryRef {
	if o == nil || IsNil(o.Country) {
		var ret CountryRef
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetCountryOk() (*CountryRef, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *Region) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given CountryRef and assigns it to the Country field.
func (o *Region) SetCountry(v CountryRef) {
	o.Country = &v
}

// GetGeometry returns the Geometry field value if set, zero value otherwise.
func (o *Region) GetGeometry() GeoJSONMultiPolygon {
	if o == nil || IsNil(o.Geometry) {
		var ret GeoJSONMultiPolygon
		return ret
	}
	return *o.Geometry
}

// GetGeometryOk returns a tuple with the Geometry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetGeometryOk() (*GeoJSONMultiPolygon, bool) {
	if o == nil || IsNil(o.Geometry) {
		return nil, false
	}
	return o.Geometry, true
}

// HasGeometry returns a boolean if a field has been set.
func (o *Region) HasGeometry() bool {
	if o != nil && !IsNil(o.Geometry) {
		return true
	}

	return false
}

// SetGeometry gets a reference to the given GeoJSONMultiPolygon and assigns it to the Geometry field.
func (o *Region) SetGeometry(v GeoJSONMultiPolygon) {
	o.Geometry = &v
}

func (o Region) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Region) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.GeonameId) {
		toSerialize["geoname_id"] = o.GeonameId
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.AdminCode) {
		toSerialize["admin_code"] = o.AdminCode
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AsciiName) {
		toSerialize["ascii_name"] = o.AsciiName
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.ParentGeonameId) {
		toSerialize["parent_geoname_id"] = o.ParentGeonameId
	}
	if !IsNil(o.Population) {
		toSerialize["population"] = o.Population
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Geometry) {
		toSerialize["geometry"] = o.Geometry
	}
	return toSerialize, nil
}

type NullableRegion struct {
	value *Region
	isSet bool
}

func (v NullableRegion) Get() *Region {
	return v.value
}

func (v *NullableRegion) Set(val *Region) {
	v.value = val
	v.isSet = true
}

func (v NullableRegion) IsSet() bool {
	return v.isSet
}

func (v *NullableRegion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegion(val *Region) *NullableRegion {
	return &NullableRegion{value: val, isSet: true}
}

func (v NullableRegion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


