/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GeoJSONGeometry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoJSONGeometry{}

// GeoJSONGeometry A bare GeoJSON geometry — the `{\"type\": ..., \"coordinates\": ...}` object itself, NOT a GeoJSON `Feature`. There is no `properties` wrapper.
type GeoJSONGeometry struct {
	// `MultiPolygon` for most areas, `Polygon` for areas with a single ring — including areas that BECOME single-ring under `?simplify=`. Do not pin this to one value.
	Type string `json:"type"`
	// Nesting depth depends on `type`: three levels for `Polygon`, four for `MultiPolygon`. Positions are `[longitude, latitude]` in EPSG:4326, per the GeoJSON specification.
	Coordinates []interface{} `json:"coordinates"`
}

type _GeoJSONGeometry GeoJSONGeometry

// NewGeoJSONGeometry instantiates a new GeoJSONGeometry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoJSONGeometry(type_ string, coordinates []interface{}) *GeoJSONGeometry {
	this := GeoJSONGeometry{}
	this.Type = type_
	this.Coordinates = coordinates
	return &this
}

// NewGeoJSONGeometryWithDefaults instantiates a new GeoJSONGeometry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoJSONGeometryWithDefaults() *GeoJSONGeometry {
	this := GeoJSONGeometry{}
	return &this
}

// GetType returns the Type field value
func (o *GeoJSONGeometry) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GeoJSONGeometry) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GeoJSONGeometry) SetType(v string) {
	o.Type = v
}

// GetCoordinates returns the Coordinates field value
func (o *GeoJSONGeometry) GetCoordinates() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Coordinates
}

// GetCoordinatesOk returns a tuple with the Coordinates field value
// and a boolean to check if the value has been set.
func (o *GeoJSONGeometry) GetCoordinatesOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Coordinates, true
}

// SetCoordinates sets field value
func (o *GeoJSONGeometry) SetCoordinates(v []interface{}) {
	o.Coordinates = v
}

func (o GeoJSONGeometry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoJSONGeometry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["coordinates"] = o.Coordinates
	return toSerialize, nil
}

func (o *GeoJSONGeometry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"coordinates",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeoJSONGeometry := _GeoJSONGeometry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeoJSONGeometry)

	if err != nil {
		return err
	}

	*o = GeoJSONGeometry(varGeoJSONGeometry)

	return err
}

type NullableGeoJSONGeometry struct {
	value *GeoJSONGeometry
	isSet bool
}

func (v NullableGeoJSONGeometry) Get() *GeoJSONGeometry {
	return v.value
}

func (v *NullableGeoJSONGeometry) Set(val *GeoJSONGeometry) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoJSONGeometry) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoJSONGeometry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoJSONGeometry(val *GeoJSONGeometry) *NullableGeoJSONGeometry {
	return &NullableGeoJSONGeometry{value: val, isSet: true}
}

func (v NullableGeoJSONGeometry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoJSONGeometry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


