/*
GeoAPI

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geoapi

import (
	"encoding/json"
)

// checks if the RegionSingleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionSingleResponse{}

// RegionSingleResponse struct for RegionSingleResponse
type RegionSingleResponse struct {
	Data *Region `json:"data,omitempty"`
}

// NewRegionSingleResponse instantiates a new RegionSingleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionSingleResponse() *RegionSingleResponse {
	this := RegionSingleResponse{}
	return &this
}

// NewRegionSingleResponseWithDefaults instantiates a new RegionSingleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionSingleResponseWithDefaults() *RegionSingleResponse {
	this := RegionSingleResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RegionSingleResponse) GetData() Region {
	if o == nil || IsNil(o.Data) {
		var ret Region
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionSingleResponse) GetDataOk() (*Region, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RegionSingleResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Region and assigns it to the Data field.
func (o *RegionSingleResponse) SetData(v Region) {
	o.Data = &v
}

func (o RegionSingleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionSingleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableRegionSingleResponse struct {
	value *RegionSingleResponse
	isSet bool
}

func (v NullableRegionSingleResponse) Get() *RegionSingleResponse {
	return v.value
}

func (v *NullableRegionSingleResponse) Set(val *RegionSingleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionSingleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionSingleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionSingleResponse(val *RegionSingleResponse) *NullableRegionSingleResponse {
	return &NullableRegionSingleResponse{value: val, isSet: true}
}

func (v NullableRegionSingleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionSingleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


