/*
GeoAPI

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geoapi

import (
	"encoding/json"
)

// checks if the Timezone type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Timezone{}

// Timezone struct for Timezone
type Timezone struct {
	Id *int64 `json:"id,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	TimezoneId *string `json:"timezone_id,omitempty"`
	GmtOffset *float64 `json:"gmt_offset,omitempty"`
	DstOffset *float64 `json:"dst_offset,omitempty"`
	RawOffset *float64 `json:"raw_offset,omitempty"`
}

// NewTimezone instantiates a new Timezone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimezone() *Timezone {
	this := Timezone{}
	return &this
}

// NewTimezoneWithDefaults instantiates a new Timezone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimezoneWithDefaults() *Timezone {
	this := Timezone{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Timezone) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timezone) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Timezone) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Timezone) SetId(v int64) {
	o.Id = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *Timezone) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timezone) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *Timezone) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *Timezone) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetTimezoneId returns the TimezoneId field value if set, zero value otherwise.
func (o *Timezone) GetTimezoneId() string {
	if o == nil || IsNil(o.TimezoneId) {
		var ret string
		return ret
	}
	return *o.TimezoneId
}

// GetTimezoneIdOk returns a tuple with the TimezoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timezone) GetTimezoneIdOk() (*string, bool) {
	if o == nil || IsNil(o.TimezoneId) {
		return nil, false
	}
	return o.TimezoneId, true
}

// HasTimezoneId returns a boolean if a field has been set.
func (o *Timezone) HasTimezoneId() bool {
	if o != nil && !IsNil(o.TimezoneId) {
		return true
	}

	return false
}

// SetTimezoneId gets a reference to the given string and assigns it to the TimezoneId field.
func (o *Timezone) SetTimezoneId(v string) {
	o.TimezoneId = &v
}

// GetGmtOffset returns the GmtOffset field value if set, zero value otherwise.
func (o *Timezone) GetGmtOffset() float64 {
	if o == nil || IsNil(o.GmtOffset) {
		var ret float64
		return ret
	}
	return *o.GmtOffset
}

// GetGmtOffsetOk returns a tuple with the GmtOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timezone) GetGmtOffsetOk() (*float64, bool) {
	if o == nil || IsNil(o.GmtOffset) {
		return nil, false
	}
	return o.GmtOffset, true
}

// HasGmtOffset returns a boolean if a field has been set.
func (o *Timezone) HasGmtOffset() bool {
	if o != nil && !IsNil(o.GmtOffset) {
		return true
	}

	return false
}

// SetGmtOffset gets a reference to the given float64 and assigns it to the GmtOffset field.
func (o *Timezone) SetGmtOffset(v float64) {
	o.GmtOffset = &v
}

// GetDstOffset returns the DstOffset field value if set, zero value otherwise.
func (o *Timezone) GetDstOffset() float64 {
	if o == nil || IsNil(o.DstOffset) {
		var ret float64
		return ret
	}
	return *o.DstOffset
}

// GetDstOffsetOk returns a tuple with the DstOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timezone) GetDstOffsetOk() (*float64, bool) {
	if o == nil || IsNil(o.DstOffset) {
		return nil, false
	}
	return o.DstOffset, true
}

// HasDstOffset returns a boolean if a field has been set.
func (o *Timezone) HasDstOffset() bool {
	if o != nil && !IsNil(o.DstOffset) {
		return true
	}

	return false
}

// SetDstOffset gets a reference to the given float64 and assigns it to the DstOffset field.
func (o *Timezone) SetDstOffset(v float64) {
	o.DstOffset = &v
}

// GetRawOffset returns the RawOffset field value if set, zero value otherwise.
func (o *Timezone) GetRawOffset() float64 {
	if o == nil || IsNil(o.RawOffset) {
		var ret float64
		return ret
	}
	return *o.RawOffset
}

// GetRawOffsetOk returns a tuple with the RawOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timezone) GetRawOffsetOk() (*float64, bool) {
	if o == nil || IsNil(o.RawOffset) {
		return nil, false
	}
	return o.RawOffset, true
}

// HasRawOffset returns a boolean if a field has been set.
func (o *Timezone) HasRawOffset() bool {
	if o != nil && !IsNil(o.RawOffset) {
		return true
	}

	return false
}

// SetRawOffset gets a reference to the given float64 and assigns it to the RawOffset field.
func (o *Timezone) SetRawOffset(v float64) {
	o.RawOffset = &v
}

func (o Timezone) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Timezone) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.TimezoneId) {
		toSerialize["timezone_id"] = o.TimezoneId
	}
	if !IsNil(o.GmtOffset) {
		toSerialize["gmt_offset"] = o.GmtOffset
	}
	if !IsNil(o.DstOffset) {
		toSerialize["dst_offset"] = o.DstOffset
	}
	if !IsNil(o.RawOffset) {
		toSerialize["raw_offset"] = o.RawOffset
	}
	return toSerialize, nil
}

type NullableTimezone struct {
	value *Timezone
	isSet bool
}

func (v NullableTimezone) Get() *Timezone {
	return v.value
}

func (v *NullableTimezone) Set(val *Timezone) {
	v.value = val
	v.isSet = true
}

func (v NullableTimezone) IsSet() bool {
	return v.isSet
}

func (v *NullableTimezone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimezone(val *Timezone) *NullableTimezone {
	return &NullableTimezone{value: val, isSet: true}
}

func (v NullableTimezone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimezone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


