/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.3
Contact: info@geosearch.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the CitySingleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CitySingleResponse{}

// CitySingleResponse struct for CitySingleResponse
type CitySingleResponse struct {
	Data *City `json:"data,omitempty"`
}

// NewCitySingleResponse instantiates a new CitySingleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCitySingleResponse() *CitySingleResponse {
	this := CitySingleResponse{}
	return &this
}

// NewCitySingleResponseWithDefaults instantiates a new CitySingleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCitySingleResponseWithDefaults() *CitySingleResponse {
	this := CitySingleResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CitySingleResponse) GetData() City {
	if o == nil || IsNil(o.Data) {
		var ret City
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CitySingleResponse) GetDataOk() (*City, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CitySingleResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given City and assigns it to the Data field.
func (o *CitySingleResponse) SetData(v City) {
	o.Data = &v
}

func (o CitySingleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CitySingleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCitySingleResponse struct {
	value *CitySingleResponse
	isSet bool
}

func (v NullableCitySingleResponse) Get() *CitySingleResponse {
	return v.value
}

func (v *NullableCitySingleResponse) Set(val *CitySingleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCitySingleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCitySingleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCitySingleResponse(val *CitySingleResponse) *NullableCitySingleResponse {
	return &NullableCitySingleResponse{value: val, isSet: true}
}

func (v NullableCitySingleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCitySingleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


