/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the Country type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Country{}

// Country struct for Country
type Country struct {
	Id *int64 `json:"id,omitempty"`
	GeonameId *int64 `json:"geoname_id,omitempty"`
	IsoCode *string `json:"iso_code,omitempty"`
	Iso3Code *string `json:"iso3_code,omitempty"`
	IsoNumeric *int32 `json:"iso_numeric,omitempty"`
	FipsCode *string `json:"fips_code,omitempty"`
	Name *string `json:"name,omitempty"`
	Capital *string `json:"capital,omitempty"`
	AreaSqKm *float64 `json:"area_sq_km,omitempty"`
	Population *int64 `json:"population,omitempty"`
	ContinentCode *string `json:"continent_code,omitempty"`
	Tld *string `json:"tld,omitempty"`
	CurrencyCode *string `json:"currency_code,omitempty"`
	CurrencyName *string `json:"currency_name,omitempty"`
	Phone *string `json:"phone,omitempty"`
	PostalCodeFormat *string `json:"postal_code_format,omitempty"`
	PostalCodeRegex *string `json:"postal_code_regex,omitempty"`
	Languages []string `json:"languages,omitempty"`
	Neighbours []string `json:"neighbours,omitempty"`
	Latitude *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
	FlagEmoji *string `json:"flag_emoji,omitempty"`
	// Country boundary. Returned by default on `GET /v1/countries/{code}` and on request via `?fields=geometry` on `GET /v1/countries`.  NOT TIER-GATED. Country geometry is served on every plan, including Free. Region geometry is gated — see the `Region` schema.
	Geometry *GeoJSONMultiPolygon `json:"geometry,omitempty"`
}

// NewCountry instantiates a new Country object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountry() *Country {
	this := Country{}
	return &this
}

// NewCountryWithDefaults instantiates a new Country object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryWithDefaults() *Country {
	this := Country{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Country) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Country) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Country) SetId(v int64) {
	o.Id = &v
}

// GetGeonameId returns the GeonameId field value if set, zero value otherwise.
func (o *Country) GetGeonameId() int64 {
	if o == nil || IsNil(o.GeonameId) {
		var ret int64
		return ret
	}
	return *o.GeonameId
}

// GetGeonameIdOk returns a tuple with the GeonameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetGeonameIdOk() (*int64, bool) {
	if o == nil || IsNil(o.GeonameId) {
		return nil, false
	}
	return o.GeonameId, true
}

// HasGeonameId returns a boolean if a field has been set.
func (o *Country) HasGeonameId() bool {
	if o != nil && !IsNil(o.GeonameId) {
		return true
	}

	return false
}

// SetGeonameId gets a reference to the given int64 and assigns it to the GeonameId field.
func (o *Country) SetGeonameId(v int64) {
	o.GeonameId = &v
}

// GetIsoCode returns the IsoCode field value if set, zero value otherwise.
func (o *Country) GetIsoCode() string {
	if o == nil || IsNil(o.IsoCode) {
		var ret string
		return ret
	}
	return *o.IsoCode
}

// GetIsoCodeOk returns a tuple with the IsoCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetIsoCodeOk() (*string, bool) {
	if o == nil || IsNil(o.IsoCode) {
		return nil, false
	}
	return o.IsoCode, true
}

// HasIsoCode returns a boolean if a field has been set.
func (o *Country) HasIsoCode() bool {
	if o != nil && !IsNil(o.IsoCode) {
		return true
	}

	return false
}

// SetIsoCode gets a reference to the given string and assigns it to the IsoCode field.
func (o *Country) SetIsoCode(v string) {
	o.IsoCode = &v
}

// GetIso3Code returns the Iso3Code field value if set, zero value otherwise.
func (o *Country) GetIso3Code() string {
	if o == nil || IsNil(o.Iso3Code) {
		var ret string
		return ret
	}
	return *o.Iso3Code
}

// GetIso3CodeOk returns a tuple with the Iso3Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetIso3CodeOk() (*string, bool) {
	if o == nil || IsNil(o.Iso3Code) {
		return nil, false
	}
	return o.Iso3Code, true
}

// HasIso3Code returns a boolean if a field has been set.
func (o *Country) HasIso3Code() bool {
	if o != nil && !IsNil(o.Iso3Code) {
		return true
	}

	return false
}

// SetIso3Code gets a reference to the given string and assigns it to the Iso3Code field.
func (o *Country) SetIso3Code(v string) {
	o.Iso3Code = &v
}

// GetIsoNumeric returns the IsoNumeric field value if set, zero value otherwise.
func (o *Country) GetIsoNumeric() int32 {
	if o == nil || IsNil(o.IsoNumeric) {
		var ret int32
		return ret
	}
	return *o.IsoNumeric
}

// GetIsoNumericOk returns a tuple with the IsoNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetIsoNumericOk() (*int32, bool) {
	if o == nil || IsNil(o.IsoNumeric) {
		return nil, false
	}
	return o.IsoNumeric, true
}

// HasIsoNumeric returns a boolean if a field has been set.
func (o *Country) HasIsoNumeric() bool {
	if o != nil && !IsNil(o.IsoNumeric) {
		return true
	}

	return false
}

// SetIsoNumeric gets a reference to the given int32 and assigns it to the IsoNumeric field.
func (o *Country) SetIsoNumeric(v int32) {
	o.IsoNumeric = &v
}

// GetFipsCode returns the FipsCode field value if set, zero value otherwise.
func (o *Country) GetFipsCode() string {
	if o == nil || IsNil(o.FipsCode) {
		var ret string
		return ret
	}
	return *o.FipsCode
}

// GetFipsCodeOk returns a tuple with the FipsCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetFipsCodeOk() (*string, bool) {
	if o == nil || IsNil(o.FipsCode) {
		return nil, false
	}
	return o.FipsCode, true
}

// HasFipsCode returns a boolean if a field has been set.
func (o *Country) HasFipsCode() bool {
	if o != nil && !IsNil(o.FipsCode) {
		return true
	}

	return false
}

// SetFipsCode gets a reference to the given string and assigns it to the FipsCode field.
func (o *Country) SetFipsCode(v string) {
	o.FipsCode = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Country) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Country) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Country) SetName(v string) {
	o.Name = &v
}

// GetCapital returns the Capital field value if set, zero value otherwise.
func (o *Country) GetCapital() string {
	if o == nil || IsNil(o.Capital) {
		var ret string
		return ret
	}
	return *o.Capital
}

// GetCapitalOk returns a tuple with the Capital field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetCapitalOk() (*string, bool) {
	if o == nil || IsNil(o.Capital) {
		return nil, false
	}
	return o.Capital, true
}

// HasCapital returns a boolean if a field has been set.
func (o *Country) HasCapital() bool {
	if o != nil && !IsNil(o.Capital) {
		return true
	}

	return false
}

// SetCapital gets a reference to the given string and assigns it to the Capital field.
func (o *Country) SetCapital(v string) {
	o.Capital = &v
}

// GetAreaSqKm returns the AreaSqKm field value if set, zero value otherwise.
func (o *Country) GetAreaSqKm() float64 {
	if o == nil || IsNil(o.AreaSqKm) {
		var ret float64
		return ret
	}
	return *o.AreaSqKm
}

// GetAreaSqKmOk returns a tuple with the AreaSqKm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetAreaSqKmOk() (*float64, bool) {
	if o == nil || IsNil(o.AreaSqKm) {
		return nil, false
	}
	return o.AreaSqKm, true
}

// HasAreaSqKm returns a boolean if a field has been set.
func (o *Country) HasAreaSqKm() bool {
	if o != nil && !IsNil(o.AreaSqKm) {
		return true
	}

	return false
}

// SetAreaSqKm gets a reference to the given float64 and assigns it to the AreaSqKm field.
func (o *Country) SetAreaSqKm(v float64) {
	o.AreaSqKm = &v
}

// GetPopulation returns the Population field value if set, zero value otherwise.
func (o *Country) GetPopulation() int64 {
	if o == nil || IsNil(o.Population) {
		var ret int64
		return ret
	}
	return *o.Population
}

// GetPopulationOk returns a tuple with the Population field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetPopulationOk() (*int64, bool) {
	if o == nil || IsNil(o.Population) {
		return nil, false
	}
	return o.Population, true
}

// HasPopulation returns a boolean if a field has been set.
func (o *Country) HasPopulation() bool {
	if o != nil && !IsNil(o.Population) {
		return true
	}

	return false
}

// SetPopulation gets a reference to the given int64 and assigns it to the Population field.
func (o *Country) SetPopulation(v int64) {
	o.Population = &v
}

// GetContinentCode returns the ContinentCode field value if set, zero value otherwise.
func (o *Country) GetContinentCode() string {
	if o == nil || IsNil(o.ContinentCode) {
		var ret string
		return ret
	}
	return *o.ContinentCode
}

// GetContinentCodeOk returns a tuple with the ContinentCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetContinentCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ContinentCode) {
		return nil, false
	}
	return o.ContinentCode, true
}

// HasContinentCode returns a boolean if a field has been set.
func (o *Country) HasContinentCode() bool {
	if o != nil && !IsNil(o.ContinentCode) {
		return true
	}

	return false
}

// SetContinentCode gets a reference to the given string and assigns it to the ContinentCode field.
func (o *Country) SetContinentCode(v string) {
	o.ContinentCode = &v
}

// GetTld returns the Tld field value if set, zero value otherwise.
func (o *Country) GetTld() string {
	if o == nil || IsNil(o.Tld) {
		var ret string
		return ret
	}
	return *o.Tld
}

// GetTldOk returns a tuple with the Tld field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetTldOk() (*string, bool) {
	if o == nil || IsNil(o.Tld) {
		return nil, false
	}
	return o.Tld, true
}

// HasTld returns a boolean if a field has been set.
func (o *Country) HasTld() bool {
	if o != nil && !IsNil(o.Tld) {
		return true
	}

	return false
}

// SetTld gets a reference to the given string and assigns it to the Tld field.
func (o *Country) SetTld(v string) {
	o.Tld = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *Country) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *Country) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *Country) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetCurrencyName returns the CurrencyName field value if set, zero value otherwise.
func (o *Country) GetCurrencyName() string {
	if o == nil || IsNil(o.CurrencyName) {
		var ret string
		return ret
	}
	return *o.CurrencyName
}

// GetCurrencyNameOk returns a tuple with the CurrencyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetCurrencyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyName) {
		return nil, false
	}
	return o.CurrencyName, true
}

// HasCurrencyName returns a boolean if a field has been set.
func (o *Country) HasCurrencyName() bool {
	if o != nil && !IsNil(o.CurrencyName) {
		return true
	}

	return false
}

// SetCurrencyName gets a reference to the given string and assigns it to the CurrencyName field.
func (o *Country) SetCurrencyName(v string) {
	o.CurrencyName = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *Country) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *Country) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *Country) SetPhone(v string) {
	o.Phone = &v
}

// GetPostalCodeFormat returns the PostalCodeFormat field value if set, zero value otherwise.
func (o *Country) GetPostalCodeFormat() string {
	if o == nil || IsNil(o.PostalCodeFormat) {
		var ret string
		return ret
	}
	return *o.PostalCodeFormat
}

// GetPostalCodeFormatOk returns a tuple with the PostalCodeFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetPostalCodeFormatOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCodeFormat) {
		return nil, false
	}
	return o.PostalCodeFormat, true
}

// HasPostalCodeFormat returns a boolean if a field has been set.
func (o *Country) HasPostalCodeFormat() bool {
	if o != nil && !IsNil(o.PostalCodeFormat) {
		return true
	}

	return false
}

// SetPostalCodeFormat gets a reference to the given string and assigns it to the PostalCodeFormat field.
func (o *Country) SetPostalCodeFormat(v string) {
	o.PostalCodeFormat = &v
}

// GetPostalCodeRegex returns the PostalCodeRegex field value if set, zero value otherwise.
func (o *Country) GetPostalCodeRegex() string {
	if o == nil || IsNil(o.PostalCodeRegex) {
		var ret string
		return ret
	}
	return *o.PostalCodeRegex
}

// GetPostalCodeRegexOk returns a tuple with the PostalCodeRegex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetPostalCodeRegexOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCodeRegex) {
		return nil, false
	}
	return o.PostalCodeRegex, true
}

// HasPostalCodeRegex returns a boolean if a field has been set.
func (o *Country) HasPostalCodeRegex() bool {
	if o != nil && !IsNil(o.PostalCodeRegex) {
		return true
	}

	return false
}

// SetPostalCodeRegex gets a reference to the given string and assigns it to the PostalCodeRegex field.
func (o *Country) SetPostalCodeRegex(v string) {
	o.PostalCodeRegex = &v
}

// GetLanguages returns the Languages field value if set, zero value otherwise.
func (o *Country) GetLanguages() []string {
	if o == nil || IsNil(o.Languages) {
		var ret []string
		return ret
	}
	return o.Languages
}

// GetLanguagesOk returns a tuple with the Languages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetLanguagesOk() ([]string, bool) {
	if o == nil || IsNil(o.Languages) {
		return nil, false
	}
	return o.Languages, true
}

// HasLanguages returns a boolean if a field has been set.
func (o *Country) HasLanguages() bool {
	if o != nil && !IsNil(o.Languages) {
		return true
	}

	return false
}

// SetLanguages gets a reference to the given []string and assigns it to the Languages field.
func (o *Country) SetLanguages(v []string) {
	o.Languages = v
}

// GetNeighbours returns the Neighbours field value if set, zero value otherwise.
func (o *Country) GetNeighbours() []string {
	if o == nil || IsNil(o.Neighbours) {
		var ret []string
		return ret
	}
	return o.Neighbours
}

// GetNeighboursOk returns a tuple with the Neighbours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetNeighboursOk() ([]string, bool) {
	if o == nil || IsNil(o.Neighbours) {
		return nil, false
	}
	return o.Neighbours, true
}

// HasNeighbours returns a boolean if a field has been set.
func (o *Country) HasNeighbours() bool {
	if o != nil && !IsNil(o.Neighbours) {
		return true
	}

	return false
}

// SetNeighbours gets a reference to the given []string and assigns it to the Neighbours field.
func (o *Country) SetNeighbours(v []string) {
	o.Neighbours = v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *Country) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *Country) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *Country) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *Country) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *Country) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *Country) SetLongitude(v float64) {
	o.Longitude = &v
}

// GetFlagEmoji returns the FlagEmoji field value if set, zero value otherwise.
func (o *Country) GetFlagEmoji() string {
	if o == nil || IsNil(o.FlagEmoji) {
		var ret string
		return ret
	}
	return *o.FlagEmoji
}

// GetFlagEmojiOk returns a tuple with the FlagEmoji field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetFlagEmojiOk() (*string, bool) {
	if o == nil || IsNil(o.FlagEmoji) {
		return nil, false
	}
	return o.FlagEmoji, true
}

// HasFlagEmoji returns a boolean if a field has been set.
func (o *Country) HasFlagEmoji() bool {
	if o != nil && !IsNil(o.FlagEmoji) {
		return true
	}

	return false
}

// SetFlagEmoji gets a reference to the given string and assigns it to the FlagEmoji field.
func (o *Country) SetFlagEmoji(v string) {
	o.FlagEmoji = &v
}

// GetGeometry returns the Geometry field value if set, zero value otherwise.
func (o *Country) GetGeometry() GeoJSONMultiPolygon {
	if o == nil || IsNil(o.Geometry) {
		var ret GeoJSONMultiPolygon
		return ret
	}
	return *o.Geometry
}

// GetGeometryOk returns a tuple with the Geometry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Country) GetGeometryOk() (*GeoJSONMultiPolygon, bool) {
	if o == nil || IsNil(o.Geometry) {
		return nil, false
	}
	return o.Geometry, true
}

// HasGeometry returns a boolean if a field has been set.
func (o *Country) HasGeometry() bool {
	if o != nil && !IsNil(o.Geometry) {
		return true
	}

	return false
}

// SetGeometry gets a reference to the given GeoJSONMultiPolygon and assigns it to the Geometry field.
func (o *Country) SetGeometry(v GeoJSONMultiPolygon) {
	o.Geometry = &v
}

func (o Country) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Country) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.GeonameId) {
		toSerialize["geoname_id"] = o.GeonameId
	}
	if !IsNil(o.IsoCode) {
		toSerialize["iso_code"] = o.IsoCode
	}
	if !IsNil(o.Iso3Code) {
		toSerialize["iso3_code"] = o.Iso3Code
	}
	if !IsNil(o.IsoNumeric) {
		toSerialize["iso_numeric"] = o.IsoNumeric
	}
	if !IsNil(o.FipsCode) {
		toSerialize["fips_code"] = o.FipsCode
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Capital) {
		toSerialize["capital"] = o.Capital
	}
	if !IsNil(o.AreaSqKm) {
		toSerialize["area_sq_km"] = o.AreaSqKm
	}
	if !IsNil(o.Population) {
		toSerialize["population"] = o.Population
	}
	if !IsNil(o.ContinentCode) {
		toSerialize["continent_code"] = o.ContinentCode
	}
	if !IsNil(o.Tld) {
		toSerialize["tld"] = o.Tld
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currency_code"] = o.CurrencyCode
	}
	if !IsNil(o.CurrencyName) {
		toSerialize["currency_name"] = o.CurrencyName
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.PostalCodeFormat) {
		toSerialize["postal_code_format"] = o.PostalCodeFormat
	}
	if !IsNil(o.PostalCodeRegex) {
		toSerialize["postal_code_regex"] = o.PostalCodeRegex
	}
	if !IsNil(o.Languages) {
		toSerialize["languages"] = o.Languages
	}
	if !IsNil(o.Neighbours) {
		toSerialize["neighbours"] = o.Neighbours
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.FlagEmoji) {
		toSerialize["flag_emoji"] = o.FlagEmoji
	}
	if !IsNil(o.Geometry) {
		toSerialize["geometry"] = o.Geometry
	}
	return toSerialize, nil
}

type NullableCountry struct {
	value *Country
	isSet bool
}

func (v NullableCountry) Get() *Country {
	return v.value
}

func (v *NullableCountry) Set(val *Country) {
	v.value = val
	v.isSet = true
}

func (v NullableCountry) IsSet() bool {
	return v.isSet
}

func (v *NullableCountry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountry(val *Country) *NullableCountry {
	return &NullableCountry{value: val, isSet: true}
}

func (v NullableCountry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


