/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the QuotaDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotaDetail{}

// QuotaDetail Structured detail accompanying a `quota_exceeded` 429. Present only on that response; absent from every other error body. It answers, in machine-readable form, what the limit is, how much was used, when it resets, and where to raise it — the same four facts `error.message` repeats in prose for the benefit of log lines and stack traces.
type QuotaDetail struct {
	// Monthly request allowance for the account's current plan.
	Limit int64 `json:"limit"`
	// Requests consumed in the current quota period.
	Used int64 `json:"used"`
	// Start of the next quota period, when `used` returns to zero. Matches the `X-RateLimit-Reset` header on the same response, expressed as RFC 3339 rather than an epoch second.
	ResetsAt time.Time `json:"resets_at"`
	// Absolute URL of the billing page where the plan can be raised. Derived server-side from configuration and never reflected from a request header or parameter.
	UpgradeUrl string `json:"upgrade_url"`
}

type _QuotaDetail QuotaDetail

// NewQuotaDetail instantiates a new QuotaDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaDetail(limit int64, used int64, resetsAt time.Time, upgradeUrl string) *QuotaDetail {
	this := QuotaDetail{}
	this.Limit = limit
	this.Used = used
	this.ResetsAt = resetsAt
	this.UpgradeUrl = upgradeUrl
	return &this
}

// NewQuotaDetailWithDefaults instantiates a new QuotaDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaDetailWithDefaults() *QuotaDetail {
	this := QuotaDetail{}
	return &this
}

// GetLimit returns the Limit field value
func (o *QuotaDetail) GetLimit() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *QuotaDetail) GetLimitOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *QuotaDetail) SetLimit(v int64) {
	o.Limit = v
}

// GetUsed returns the Used field value
func (o *QuotaDetail) GetUsed() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *QuotaDetail) GetUsedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *QuotaDetail) SetUsed(v int64) {
	o.Used = v
}

// GetResetsAt returns the ResetsAt field value
func (o *QuotaDetail) GetResetsAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ResetsAt
}

// GetResetsAtOk returns a tuple with the ResetsAt field value
// and a boolean to check if the value has been set.
func (o *QuotaDetail) GetResetsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResetsAt, true
}

// SetResetsAt sets field value
func (o *QuotaDetail) SetResetsAt(v time.Time) {
	o.ResetsAt = v
}

// GetUpgradeUrl returns the UpgradeUrl field value
func (o *QuotaDetail) GetUpgradeUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpgradeUrl
}

// GetUpgradeUrlOk returns a tuple with the UpgradeUrl field value
// and a boolean to check if the value has been set.
func (o *QuotaDetail) GetUpgradeUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpgradeUrl, true
}

// SetUpgradeUrl sets field value
func (o *QuotaDetail) SetUpgradeUrl(v string) {
	o.UpgradeUrl = v
}

func (o QuotaDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotaDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["limit"] = o.Limit
	toSerialize["used"] = o.Used
	toSerialize["resets_at"] = o.ResetsAt
	toSerialize["upgrade_url"] = o.UpgradeUrl
	return toSerialize, nil
}

func (o *QuotaDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"limit",
		"used",
		"resets_at",
		"upgrade_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuotaDetail := _QuotaDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuotaDetail)

	if err != nil {
		return err
	}

	*o = QuotaDetail(varQuotaDetail)

	return err
}

type NullableQuotaDetail struct {
	value *QuotaDetail
	isSet bool
}

func (v NullableQuotaDetail) Get() *QuotaDetail {
	return v.value
}

func (v *NullableQuotaDetail) Set(val *QuotaDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaDetail(val *QuotaDetail) *NullableQuotaDetail {
	return &NullableQuotaDetail{value: val, isSet: true}
}

func (v NullableQuotaDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


