/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.3
Contact: info@geosearch.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpgradeDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeDetail{}

// UpgradeDetail Structured detail accompanying a `tier_upgrade_required` 403. Present only on that response; absent from every other error body.  ONE FIELD, DELIBERATELY. It says where to go and claims nothing else. It carries no limit, no usage and no reset instant, because none of those describe a plan that simply does not include the feature — there is no quantity to wait for and nothing resets.
type UpgradeDetail struct {
	// Absolute URL of the billing page where the plan can be raised. Derived server-side from configuration and never reflected from a request header or parameter.
	UpgradeUrl string `json:"upgrade_url"`
}

type _UpgradeDetail UpgradeDetail

// NewUpgradeDetail instantiates a new UpgradeDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeDetail(upgradeUrl string) *UpgradeDetail {
	this := UpgradeDetail{}
	this.UpgradeUrl = upgradeUrl
	return &this
}

// NewUpgradeDetailWithDefaults instantiates a new UpgradeDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeDetailWithDefaults() *UpgradeDetail {
	this := UpgradeDetail{}
	return &this
}

// GetUpgradeUrl returns the UpgradeUrl field value
func (o *UpgradeDetail) GetUpgradeUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpgradeUrl
}

// GetUpgradeUrlOk returns a tuple with the UpgradeUrl field value
// and a boolean to check if the value has been set.
func (o *UpgradeDetail) GetUpgradeUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpgradeUrl, true
}

// SetUpgradeUrl sets field value
func (o *UpgradeDetail) SetUpgradeUrl(v string) {
	o.UpgradeUrl = v
}

func (o UpgradeDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["upgrade_url"] = o.UpgradeUrl
	return toSerialize, nil
}

func (o *UpgradeDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"upgrade_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpgradeDetail := _UpgradeDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpgradeDetail)

	if err != nil {
		return err
	}

	*o = UpgradeDetail(varUpgradeDetail)

	return err
}

type NullableUpgradeDetail struct {
	value *UpgradeDetail
	isSet bool
}

func (v NullableUpgradeDetail) Get() *UpgradeDetail {
	return v.value
}

func (v *NullableUpgradeDetail) Set(val *UpgradeDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeDetail(val *UpgradeDetail) *NullableUpgradeDetail {
	return &NullableUpgradeDetail{value: val, isSet: true}
}

func (v NullableUpgradeDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


