/*
GeoSearch

Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

API version: 1.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geosearch

import (
	"encoding/json"
)

// checks if the RegionRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionRef{}

// RegionRef struct for RegionRef
type RegionRef struct {
	Id *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	AdminCode *string `json:"admin_code,omitempty"`
}

// NewRegionRef instantiates a new RegionRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionRef() *RegionRef {
	this := RegionRef{}
	return &this
}

// NewRegionRefWithDefaults instantiates a new RegionRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionRefWithDefaults() *RegionRef {
	this := RegionRef{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RegionRef) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionRef) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RegionRef) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *RegionRef) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RegionRef) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionRef) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RegionRef) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RegionRef) SetName(v string) {
	o.Name = &v
}

// GetAdminCode returns the AdminCode field value if set, zero value otherwise.
func (o *RegionRef) GetAdminCode() string {
	if o == nil || IsNil(o.AdminCode) {
		var ret string
		return ret
	}
	return *o.AdminCode
}

// GetAdminCodeOk returns a tuple with the AdminCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionRef) GetAdminCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AdminCode) {
		return nil, false
	}
	return o.AdminCode, true
}

// HasAdminCode returns a boolean if a field has been set.
func (o *RegionRef) HasAdminCode() bool {
	if o != nil && !IsNil(o.AdminCode) {
		return true
	}

	return false
}

// SetAdminCode gets a reference to the given string and assigns it to the AdminCode field.
func (o *RegionRef) SetAdminCode(v string) {
	o.AdminCode = &v
}

func (o RegionRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AdminCode) {
		toSerialize["admin_code"] = o.AdminCode
	}
	return toSerialize, nil
}

type NullableRegionRef struct {
	value *RegionRef
	isSet bool
}

func (v NullableRegionRef) Get() *RegionRef {
	return v.value
}

func (v *NullableRegionRef) Set(val *RegionRef) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionRef) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionRef(val *RegionRef) *NullableRegionRef {
	return &NullableRegionRef{value: val, isSet: true}
}

func (v NullableRegionRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


